# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gsever <gsever@student.42kocaeli.com.tr    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/19 22:29:33 by gsever            #+#    #+#              #
#    Updated: 2022/03/20 01:58:11 by gsever           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME 		:=
SERVER		:= server
CLIENT		:= client

LIBFT_A		:= ./libft/libft.a
CLIENT_SRC	:= client.c
SERVER_SRC	:= server.c

CC			:= cc
FLAGS		:= -Wall -Werror -Wextra

$(NAME):

$(CLIENT):

$(SERVER):

$(LIBFT_A):
	make -C libft

all:

bonus:

clean:

fclean:

re:

.PHONY: all clean fclean re bonus libft